:sparkles: [services] Add command `cutty link <template>` (#470)
* :recycle: [functional] Improve error message when cutty fails during tests

* :white_check_mark: [functional] Add test for `cutty link --help`

* :sparkles: [entrypoints] Add stub for `cutty link`

Omitting the `@click.argument` decorator results in a mysterious mypy error:

  src/cutty/entrypoints/cli/__init__.py:13:21: error: Value of type variable "_F" of "__call__" of "ContextDecorator" cannot be "function"  [type-var]
          registercommand(fatal(command))
                          ^
  src/cutty/entrypoints/cli/__init__.py:13:21: error: Argument 1 has incompatible type "function"; expected "Callable[..., Any]"  [arg-type]
          registercommand(fatal(command))
                          ^

* :white_check_mark: [functional] Add test for `cutty link` adding cutty.json

* :sparkles: [entrypoints] Add basic functionality for `cutty link`

* :recycle: [services] Extract function `link` from `entrypoints.cli.link` to `services.link`

* :recycle: [functional] Extract fixture `project` from `cutty link` tests

* :recycle: [functional] Remove unused fixture from `cutty create` test

* :white_check_mark: [functional] Add test for `cutty link --cwd`

* :sparkles: [services] Add `cutty link --cwd=<project>`

* :white_check_mark: [functional] Add test for `cutty link <template> <var>=<value>`

* :sparkles: [services] Add `cutty link <template> <var>=<value>`

* :white_check_mark: [functional] Add test for `cutty link --no-input`

* :sparkles: [services] Add `cutty link --no-input`

* :white_check_mark: [functional] Add test for `cutty link --directory=<directory>`

* :sparkles: [services] Add `cutty link --directory=<directory>`

* :white_check_mark: [functional] Add test for `cutty link --checkout=<revision>`

* :sparkles: [services] Add `cutty link --checkout=<revision>`