Fix ill-advised inheritance of api.generate.Cleanup
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/cjolowicz/Library/Caches/pypoetry/virtualenvs/cutty-HoqLTmtI-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cjolowicz/Library/Caches/pypoetry/virtualenvs/cutty-HoqLTmtI-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/cjolowicz/Library/Caches/pypoetry/virtualenvs/cutty-HoqLTmtI-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cjolowicz/Library/Caches/pypoetry/virtualenvs/cutty-HoqLTmtI-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cjolowicz/Library/Caches/pypoetry/virtualenvs/cutty-HoqLTmtI-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cjolowicz/Code/github.com/cjolowicz/cutty/src/cutty/cli/update.py", line 47, in update
    api.update(
  File "/Users/cjolowicz/Code/github.com/cjolowicz/cutty/src/cutty/api/update.py", line 48, in update
    engine.generate(project.path.parent)
  File "/Users/cjolowicz/Code/github.com/cjolowicz/cutty/src/cutty/api/engine.py", line 22, in generate
    self.generator.generate(output_dir)
  File "/Users/cjolowicz/Code/github.com/cjolowicz/cutty/src/cutty/api/generate.py", line 41, in generate
    cleanup.cancel()
  File "/Users/cjolowicz/Code/github.com/cjolowicz/cutty/src/cutty/api/generate.py", line 23, in cancel
    self.pop_all()
  File "/Users/cjolowicz/.pyenv/versions/3.8.4/lib/python3.8/contextlib.py", line 390, in pop_all
    new_stack = type(self)()
TypeError: __init__() missing 1 required positional argument: 'path'